# Generated by Django 6.0.4 on 2026-08-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=200)),
                ('receipe_desc', models.TextField()),
                ('receipe_image', models.ImageField(upload_to='receipes')),
            ],
        ),
    ]
