# Generated by Django 6.0.4 on 2026-08-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_studentid_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
